---
version: '3.6'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    container_name: elasticsearch
    ports: ['9200:9200']

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.1
    container_name: kibana
    ports: ['5601:5601']
    depends_on: ['elasticsearch']

  nats:
    image: nats:1.3.0
    container_name: nats
    hostname: nats-server

#cuoco: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRkYW50b25pbyIsImZ1bGxOYW1lIjoiRGF2aWRlIEQnQW50b25pbyIsInR5cGUiOiJjb29rIiwiaWF0IjoxNTQyOTY1NTQ2fQ.VN1CcxPU_OEA5ICCnmYkWMxKAiLI2mN-mMXtTTMCRUw
#cameriere: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRkYW50b25pbzIiLCJmdWxsTmFtZSI6IkRhdmlkZSBEJ0FudG9uaW8iLCJ0eXBlIjoid2FpdGVyIiwiaWF0IjoxNTQyOTY1NTc2fQ.t7wTZZuP_HeTnFOA_AVY_OV9jyzLyWTUt1-X2JWNdzY